name: Liquibase Status

on:
  push:
  workflow_dispatch: {}

jobs:
  liquibase-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Liquibase Status
      uses: liquibase-github-actions/status@v4.31.0
      with:
        changelogFile: changelog-master.xml
        url: ${{ secrets.JDBC_URL }}
        username: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASS }}
        classpath: "lib/mysql-connector-j-9.2.0.jar"