name: Liquibase Validate

on:
  push:
  workflow_dispatch: {}

jobs:
  liquibase-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Liquibase Validate
      uses: liquibase-github-actions/validate@v4.31.0
      with:
        changelogFile: main-changelog.xml
        url: ${{ secrets.JDBC_URL }}
        username: ${{ secrets.DB_USER }}
        password: ${{ secrets.DB_PASS }}
        classpath: "lib/mysql-connector-j-9.2.0.jar"